
<script type="text/javascript">
if (typeof jQuery == 'undefined'){
    document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script> 
<!-- <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="//cloud.github.com/downloads/wycats/handlebars.js/handlebars-1.0.0.beta.6.js" type="text/javascript" charset="utf-8"></script>
<?php  $i=0;$t=0; ?>
<?php
	$txtype='';
	$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
	if($isPartner==1){
		$rightseller=Mage::getModel('marketplace/userprofile')->isRightSeller($this->getRequest()->getParam('id'));
		if($rightseller){
			$url= $_SERVER['REQUEST_URI'];
			$urlarr=explode('/id/',$url);
			$product =  Mage::getModel('catalog/product')->load($urlarr[1])->getData();	
			$readresult=Mage::getModel('customattribute/customattribute')->getFrontShowAttributes($product['attribute_set_id']);

			$isbundle=$product['type_id'];

			foreach($readresult as $attr) {
				$attribute = Mage::getModel('catalog/resource_eav_attribute')->load($attr['attribute_id']); ?>
				<?php 
				$apply_to=explode(',', $attribute->getData('apply_to'));
				if(in_array($isbundle, $apply_to) || $attribute->getData('apply_to')==''){
				if($attribute['is_user_defined']  == 1){ ?>
				<li>
					<label id="<?php echo $attribute['attribute_code']?>" class="<?php if($attribute['is_required']){ echo "required";} ?>"><?php echo $attribute->getStoreLabel(); ?><?php if($attribute['frontend_input'] == 'price'){ ?><b><?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); echo  " (". Mage::app()->getLocale()->currency( $currency_code )->getSymbol().")"; ?></b><?php }?>:</label>
					<div class="input-box">
						<?php if($attribute['frontend_input'] == 'select'||$attribute['frontend_input']=='multiselect'||$attribute['frontend_input']=='boolean'){ 
							$fix="";
							$multiselect="";
							if($attribute['frontend_input']=='multiselect'){
								$fix="[]";	
								$multiselect="multiple";
							}
							
							?>
							<select class="myinput-text <?php if($attribute['is_required']) {echo 'required-entry'.' '.$attribute['frontend_class']; } ?> input-text" name="<?php echo $attribute['attribute_code'].$fix;?>" <?php echo $multiselect;?>>
								<?php $attributeOptions = $attribute->setStoreId(Mage::app()->getStore()->getId())->getSource()->getAllOptions();
								foreach($attributeOptions as $each){ 		
									$values=explode(',',$product[$attribute['attribute_code']]);
									$selected="";					
									if(in_array($each["value"],$values)){
										$selected= "selected=='selected'";
									} ?>
								  <option <?php echo $selected; ?> value="<?php echo $each["value"]; ?>"><?php echo $each["label"];  ?></option>
								<?php } ?>
							</select>
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'text'){ ?>
							<input class="<?php if($attribute['is_required']) {echo 'required-entry'.' '.$attribute['frontend_class']; } ?> input-text" type="text" value="<?php $x=$attribute['attribute_code']; echo $product[$x]; ?>" name="<?php echo $attribute['attribute_code'];?>" />
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'price'){ ?>
							<input class="<?php if($attribute['is_required']) {echo 'required-entry'; } ?> input-text" type="number" value="<?php $x=$attribute['attribute_code'];  ?><?php  $baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
													$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
													$price = Mage::helper('directory')->currencyConvert($product[$x], $baseCurrencyCode, $currentCurrencyCode);
													  echo number_format($price, 2, '.', ''); ?>" name="<?php echo $attribute['attribute_code'];?>" />
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'weight'){ ?>
							<input class="<?php if($attribute['is_required']) {echo 'required-entry'; } ?> input-text" type="text" value="<?php $x=$attribute['attribute_code']; echo $product[$x]; ?>" name="<?php echo $attribute['attribute_code'];?>" />
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'date'){ ?>
							<input class="<?php if($attribute['is_required']) {echo 'required-entry'; } ?> input-text datetype" type="text" value="<?php $x=$attribute['attribute_code']; echo date('y/m/d', strtotime($product[$x])); ?>" name="<?php echo $attribute['attribute_code'];?>" />
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'textarea'){ ?>
							<textarea class="<?php if($attribute['is_required']) {echo 'required-entry'; } ?> input-text" rows="5" cols="75" id="textar" name="<?php echo $attribute['attribute_code'];?>" /><?php $x=$attribute['attribute_code']; echo $product[$x]; ?></textarea>
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'media_image'){ ?>
							<input class="<?php if($attribute['is_required']) {echo 'required-entry'; } ?> input-text" type="file" name="<?php echo $attribute['attribute_code'];?>" value="<?php echo $product[$attribute['attribute_code']] ?>" />
							<?php if($product[$attribute['attribute_code']]){  ?>
							<img src="<?php echo $this->helper('catalog/image')->init(Mage::getModel('catalog/product')->load($urlarr[1]), $attribute['attribute_code'])->resize(100); ?>">
							<?php } ?>
						<?php } ?>
						<?php if($attribute['frontend_input'] == 'gallery'){ ?>
							<input class="<?php if($attribute['is_required']) {echo 'required-entry'; } ?> input-text" type="file" name="<?php echo $attribute['attribute_code'];?>" />
						<?php } ?>
					
						<?php if($attribute['frontend_input'] == 'weee'){
							$txtype=$attribute['attribute_code'];
							?>
							<input type="hidden" name="<?php echo $txtype; ?>[]">
							<div class="producttax">
								<div class="wk_mp_option-box">
									<ul class="wk_mp_headcus ul_first">
										<li><?php echo Mage::helper('customattribute')->__('Country/State ') ?></li>
										<li><?php echo Mage::helper('customattribute')->__('tax') ?></li>
										<li><?php echo Mage::helper('customattribute')->__('Action') ?></li>
										<li>
											<button class="button addproducttax" title="Add" type="button">
												<span>
													<span><?php echo Mage::helper('customattribute')->__('Add') ?></span>
												</span>
											</button>
										</li>
									</ul>
								</div>
								
								<?php if(isset($product[$txtype])) { ?>
									<?php if(count($product[$txtype])!=0){
										foreach($product[$txtype] as $taxtype){ ?>
											<ul class="wk_mp_headcus">
												<li>
													<select name="<?php echo $txtype; ?>[<?php echo $i; ?>][country]" class="country">
														<?php  $countryList = Mage::getModel('directory/country')
																				->getResourceCollection()
																				->loadByStore()
																				->toOptionArray(true);
																foreach($countryList as $value){
																	if($value['value']!=''){
																		?>
																	<option value="<?php echo $value['value'];?>" <?php if($taxtype['country'] == $value['value']) echo " selected"; ?> ><?php echo $value['label'] ?></option>
																	<?php }
																 }?>
													</select>
													<select name="<?php echo $txtype; ?>[<?php echo $i; ?>][state]" class="state">
														<option value="0">*</option>
													<?php
														$regionCollection = Mage::getModel('directory/region')
																				->getResourceCollection()
													                            ->addCountryFilter($taxtype['country'])
													                            ->load();
													    foreach($regionCollection as $region){
													    	if($taxtype['state']!='0' && $region['region_id']==$taxtype['state']){
																$region = Mage::getModel('directory/region')->load($taxtype['state']);
																?>
																	<option value="<?php echo $taxtype['state'] ?>" selected><?php echo $region->getName(); ?></option>
																<?php
															}else{
																?>
																	<option value="<?php echo $region['region_id'] ?>"><?php echo $region['default_name']; ?></option>
																<?php
															}
													    } ?>
													</select>
												</li>
												<li>
													<div class="input-box">
														<input class="input-text" type="text" name="<?php echo $txtype; ?>[<?php echo $i; ?>][price]" value="<?php echo $taxtype['value']; ?>">
													</div>
												</li>
												<li>
													<div class="input-box">
														<input class="input-text" type="hidden" name="<?php echo $txtype; ?>[<?php echo $i; ?>][website_id]" value="0" />
													</div>
												</li>
												<li>
													<button class="button taxdelete" title="Delete" type="button">
														<span>
															<span><?php echo Mage::helper('customattribute')->__('Delete') ?></span>
														</span>
													</button>
												</li>
											</ul> <?php
										 $i++;
										}
											?>
										
									<?php }
								}
							?>
						</div> <?php
						 } ?>
					</div>
				</li>
				<?php }			 
				 elseif($attribute['is_user_defined']  == 0) {
					if($attribute['attribute_code']=='special_price'){ ?>
						<li>
							<label><?php echo $attribute->getStoreLabel(); ?><b><?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); echo  " (". Mage::app()->getLocale()->currency( $currency_code )->getSymbol().")"; ?></b>:</label>
							<div class="input-box">
								<input type="special_price" class="required-entry input-text" name="special_price" id="special_price" value="<?php  $baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
													$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
													$price = Mage::helper('directory')->currencyConvert($product['special_price'], $baseCurrencyCode, $currentCurrencyCode);
													  echo number_format($price, 2, '.', ''); ?>"/>
							</div>
						</li>
						<li>
							<label><?php echo Mage::helper('customattribute')->__('Special Price From') ?>:</label>
							<div class="input-box">
								<input name="special_from_date" id="special_from_date" class="required-entry input-text" value="<?php echo $product['special_from_date']; ?>"/>
							</div>
						</li>
						<li>
							<label><?php echo Mage::helper('customattribute')->__('Special Price To') ?>:</label>
							<div class="input-box">
								<input name="special_to_date" id="special_to_date" class="required-entry input-text" value="<?php echo $product['special_to_date']; ?>"/>
							</div>
						</li>	
					<?php }
					elseif($attribute['attribute_code']=='tier_price'){ ?>
						<li class="tierprice">
							<input type="hidden" name="tier_price[]">
							<label><?php echo $attribute->getStoreLabel(); ?>:</label>
							<div class="wk_mp_option-box">
								<ul class="wk_mp_headcus ul_first">
									<li><?php echo Mage::helper('customattribute')->__('Special Price To') ?></li>
									<li><?php echo Mage::helper('customattribute')->__('Qty') ?></li>
									<?php
									if($isbundle=='bundle'){ ?>
										<li class="bundle"><?php echo Mage::helper('customattribute')->__('Percent Discount') ?><b><?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); echo  " (". Mage::app()->getLocale()->currency( $currency_code )->getSymbol().")"; ?></b></li>
								<?php	}else{ ?>
											<li><?php echo Mage::helper('customattribute')->__('Price') ?><b><?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); echo  " (". Mage::app()->getLocale()->currency( $currency_code )->getSymbol().")"; ?></b></li>
								<?php	} ?>
									<li><?php echo Mage::helper('customattribute')->__('Action') ?></li>
									<li>
										<button class="button addtierprice" title="Add" type="button">
											<span>
												<span><?php echo Mage::helper('customattribute')->__('Add') ?></span>
											</span>
										</button>
									</li>
								</ul>
								<?php if(count($product['tier_price'])==0): ?>

									<ul class="wk_mp_headcus">
										<li>
											<select name="tier_price[<?php echo $t ?>][cust_group]" >
												<option value="32000">ALL GROUPS</option>
												<?php  $customer_group = Mage::getModel('customer/group')->getCollection(); 
														foreach($customer_group as $group){ ?>
															<option value="<?php echo $group->getCustomerGroupId(); ?>"><?php echo $group->getCustomerGroupCode(); ?></option>
														<?php }	?>
											</select>
										</li>
										<li>
											<div class="input-box">
												<input class="input-text" type="text" name="tier_price[<?php echo $t ?>][price_qty]" onKeyPress="return numbersonly(this, event, true);">
											</div>
										</li>
										<li>
											<div class="input-box">
												<input type="text" class="input-text tierprice"  name="tier_price[<?php echo $t ?>][price]" onKeyPress="return numbersonly(this, event, true);" >
											</div>
										</li>
										<li>
											<button class="button delete" title="Delete" type="button">
												<span>
													<span><?php echo Mage::helper('customattribute')->__('Delete') ?></span>
												</span>
											</button>
										</li>
									</ul>
									<?php $t++; ?>
								<?php  else: ?>
									<?php foreach ($product['tier_price'] as $value): ?>
										<ul class="wk_mp_headcus">
											<li>
												<select name="tier_price[<?php echo $t ?>][cust_group]" >
													<option value="32000">ALL GROUPS</option>
													<?php $customer_group = new Mage_Customer_Model_Group();
													$allGroups  = $customer_group->getCollection()->toOptionHash();
													foreach($allGroups as $key=>$allGroup){
														$customerGroup[$key]=array('value'=>$allGroup,'label'=>$allGroup);	?>
														<option <?php if($value['cust_group']==$key) echo 'selected'; ?> value="<?php echo $key; ?>"><?php echo $allGroup; ?></option>
													<?php } ?>
												</select>
											</li>
											<li>
												<div class="input-box">
													<input type="text" class="input-text" name="tier_price[<?php echo $t ?>][price_qty]" value="<?php echo $value['price_qty']; ?>" onKeyPress="return numbersonly(this, event, true);">
												</div>
											</li>
											<li>
												<div class="input-box">
													<input type="text" name="tier_price[<?php echo $t ?>][price]" class="input-text tierprice"  value="<?php  $baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
													$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
													$price = Mage::helper('directory')->currencyConvert($value['price'], $baseCurrencyCode, $currentCurrencyCode);
													  echo number_format($price, 2, '.', ''); ?>" onKeyPress="return numbersonly(this, event, true);">
												</div>
											</li>
											<li>
												<button class="button delete" title="Delete" type="button">
													<span>
														<span><?php echo Mage::helper('customattribute')->__('Delete') ?></span>
													</span>
												</button>
											</li>
										</ul>
										<?php $t++; ?>
									<?php endforeach; ?>
								<?php endif ?>
							</div>
						</li>
					<?php  }
				}
			} }	?>
<script id="wk_customattr_template" type="text/x-handlebars-template">
	<ul class="wk_mp_headcus">
		<li>
			<select name="tier_price[${index}][cust_group]" >
				<option value="32000">ALL GROUPS</option>
				<?php  $customer_group = Mage::getModel('customer/group')->getCollection(); 
						foreach($customer_group as $group){ ?>
							<option value="<?php echo $group->getCustomerGroupId(); ?>"><?php echo $group->getCustomerGroupCode(); ?></option>
						<?php }	?>
			</select>
		</li>
		<li>
			<div class="input-box">
				<input class="input-text" type="text" name="tier_price[${index}][price_qty]" onKeyPress="return numbersonly(this, event, true);">
			</div>
		</li>
		<li>
			<div class="input-box">
				<input type="text" class="input-text validate-zero-or-greater tierprice" name="tier_price[${index}][price]">
			</div>
		</li>
		<li>
			<button class="button delete" title="Delete" type="button">
				<span>
					<span><?php echo Mage::helper('customattribute')->__('Delete') ?></span>
				</span>
			</button>
		</li>
	</ul>
</script>
<script id="wk_producttax_template" type="text/x-jquery-tmpl">
	<ul class="wk_mp_headcus">
		<li>
			<select name="<?php echo $txtype; ?>[${index}][country]" class="country">
				<?php  $countryList = Mage::getModel('directory/country')->getResourceCollection()
										->loadByStore()
										->toOptionArray(true);
						foreach($countryList as $value){
							if($value['value']!=''){
								?>
							<option value="<?php echo $value['value']; ?>"><?php echo $value['label'] ?></option>
							<?php }
						 }	?>
			</select>
			<select name="<?php echo $txtype; ?>[${index}][state]" id="state">
				<option value="*">*</option>
			</select>
		</li>
		<li>
			<div class="input-box">
				<input class="input-text" type="text" name="<?php echo $txtype; ?>[${index}][price]" onKeyPress="return numbersonly(this, event, true);">
			</div>
		</li>
		<li>
			<div class="input-box">
				<input class="input-text" type="hidden" name="<?php echo $txtype; ?>[${index}][website_id]" value="0" />
			</div>
		</li>
		<li>
			<button class="button taxdelete" title="Delete" type="button">
				<span>
					<span><?php echo Mage::helper('customattribute')->__('Delete') ?></span>
				</span>
			</button>
		</li>
	</ul>
</script>
<script src="<?php echo $this->getSkinUrl('marketplace/js/jquery.tmpl.min.js') ?>" type="text/javascript"></script>			
<script>
jQuery.noConflict();
(function(jQuery){
	var count_of_sample_row = <?php echo $i;?>;
	var tier_count = <?php echo $t;?>;
	jQuery(document).on('change','.country',function(){
		var thiss=jQuery(this);
		jQuery(this).next().empty().append("<option value=0>*</option>");
		var country=jQuery(this).val();
		jQuery.ajax({
	        type: "POST",
	        url:'<?php echo $this->getUrl('customattribute/index/getregiondata') ?>',
	        dataType: "JSON",
	        data: {
	            country: country
	        },
	        success: function(response) {
	        	if(jQuery(thiss).next().children().length){
	        		jQuery(thiss).next().children().remove();
	        		jQuery(thiss).next().append("<option value='0'>*</option>");
	        	}
	        	var i=0;
	            jQuery.each(response,function(key,value){
	            	jQuery(thiss).next().append("<option value="+response[i]['region_id']+">"+response[i]['name']+"</option>");
	            	i++;
	            })
	        },
	        error: function(response) {
	            console.log(response);
	        }
    	});

	});

	if('<?php echo $isbundle ?>' =='bundle'){
		jQuery('.tierprice').on('keyup',function(){
			if(jQuery(this).val()>100){
				console.log(jQuery(this).val());
				alert('price discount should be less than or equal to 100');
				jQuery(this).val('');
			}
		});	
	}



	jQuery('.producttax').delegate('.addproducttax','click',function(){
		jQuery("#wk_producttax_template").tmpl([{'index':count_of_sample_row}]).appendTo(".producttax");
		count_of_sample_row++;
	});

	jQuery('.producttax').delegate('.taxdelete','click',function(){
		jQuery(this).parents('.wk_mp_headcus').remove();
	});

	jQuery(function(){
		jQuery(".datetype").datepicker();
	});
	jQuery('.tierprice').delegate('.addtierprice','click',function(){
		jQuery("#wk_customattr_template").tmpl([{'index':tier_count}]).appendTo(".tierprice .wk_mp_option-box");
		tier_count++;
	});
	var count=1;
/*	jQuery( "#special_from_date" ).datepicker();
	jQuery( "#special_to_date" ).datepicker();*/

	jQuery('body').delegate('.delete-product-option','click',function(event){
		jQuery(this).parent().parent().remove();
	});
	jQuery('.tierprice').delegate('.delete','click',function(){
		jQuery(this).parents('.wk_mp_headcus').remove();
	});
})(jQuery);
function numbersonly(myfield, e, dec){
		var key;
		var keychar;
		if (window.event)
			key = window.event.keyCode;
		else if (e)
			key = e.which;
		else
			return true;
		keychar = String.fromCharCode(key);
		if ((key==null) || (key==0) || (key==8) ||
			(key==9) || (key==13) || (key==27) )
			return true;
		else if ((("0123456789").indexOf(keychar) > -1))
			return true;
		else
			return false;
	}
</script>
<?php } }?>
