<?php
$partner=$this->getProfileDetail();
$logo=$partner->getlogopic()==''?"noimage.png":$partner->getlogopic();
$logo=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$logo;
?>
<div class="block block-list block-collection">
	<div class="block-title">
		<strong><span><?php echo Mage::helper('marketplace')->__('View Collection') ?> :</span> </strong>
	</div>
	<div class="block-content">
		<?php echo $this->getChildHtml();?>
		<a href="<?php echo  Mage::getUrl('marketplace/seller/collection').$partner->getprofileurl(); ?>" title="<?php echo Mage::helper('marketplace')->__('Visit Complete Collection')?>" id="siteconnect"><?php echo Mage::helper('marketplace')->__('View Collection')?></a>
		<span class="profile-view">
		<a href="<?php echo  Mage::getUrl('marketplace/seller/profile').$partner->getprofileurl() ?>" title="<?php echo Mage::helper('marketplace')->__('Visit Profile')?>" id="profileconnect"><?php echo Mage::helper('marketplace')->__('View Profile')?></a>
		<span class="collection-hover-div">
			<a href="<?php echo Mage::getUrl('marketplace/seller/profile').$partner->getprofileurl();?>">
				<img class="hover-bannerpicrs" src="<?php echo $logo;?>"/>
			</a>
			<?php echo $partner->getcompdesi(); ?>
		</span>
		</span>
	</div>
</div>
