<script type="text/javascript">
	if (typeof $wk_jq == 'undefined'){
		document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
</script> 
<?php
	$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
	$customerid=Mage::getSingleton('customer/session')->getCustomerId();
	if($isPartner==1){
		$rightseller=Mage::getModel('marketplace/userprofile')->isRightSeller($this->getRequest()->getParam('id'));
		if($rightseller){
?>
<script type="text/javascript">
  bkLib.onDomLoaded(function(){
	new nicEditor({fullPanel : true}).panelInstance('description');
	new nicEditor({fullPanel : true}).panelInstance('short_description');     
  });
</script>
<?php
	$urlid=$this->getRequest()->getParam('id');
	$loadpro =Mage::getModel('catalog/product')->load($urlid);
	$cat=$loadpro->getCategoryIds();
	$qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($urlid)->getQty();				
	$categories = Mage::getModel('catalog/category')->getCollection()->addAttributeToSelect('*')->addIsActiveFilter();
	$allcatid = array();
	$k=0;
	foreach($categories as $c){
		$allcatid[$k] = $c->getId();
		$k++;
	}
	$finalcat=array_shift($allcatid);	
	$partner=Mage::getModel('marketplace/userprofile')->getPartnerProfileById($customerid); ?>
	
	<div class="page-title">
		<h1><?php echo Mage::helper('marketplace')->__('Edit Simple Product') ?></h1>
	</div>
	<form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedsimple') ?>" enctype="multipart/form-data" method="post" id="form-customer-product-editPost">
		<div class="fieldset">
			<input type="hidden" name="productid" value="<?php echo $urlid; ?>" />
			<h4 class="legend"><?php echo Mage::helper('marketplace')->__('Simple Product') ?></h4>
			<ul class="form-list" id="wk_bodymain">
				<?php if(($partner['twitterid']=='')||($partner['facebookid']=='')||($partner['bannerpic']=='')||($partner['logopic']=='')||($partner['complocality']=='')||($partner['countrypic']=='')||($partner['compdesi']=='')){?>
					<marquee><h4 class="wk_marquee"><?php echo Mage::helper('marketplace')->__('Please Complete your Profile..')?></h4></marquee>
				<?php } ?>
				<li>
					<label class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Product Category') ?>:</label>
					<div class="input-box">
						<select id="category" class="required-entry" name="category[]" multiple="yes">
							<?php foreach($allcatid as $keycat){ 
								$flag=0;
								foreach($cat as $category){ 
									if($keycat==$category){?>
										<option selected="selected" value="<?php echo $keycat;?>"><?php echo Mage::getModel("catalog/category")->load($keycat)->getName() ?></option>
									<?php
										$flag=1;
									}
								}										
								if($flag==0) {?>
										<option value="<?php echo $keycat;?>"><?php echo Mage::getModel("catalog/category")->load($keycat)->getName() ?></option>
								<?php 
								} 
							} ?>							
						</select>
					</div>
				</li>
				<li>
					<label class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Product Name') ?>:</label>
					<div class="input-box">
						<input type="name" class="required-entry input-text" name="name" id="name" value="<?php echo $loadpro->getName(); ?>" />
					</div>
				</li>
				<li>
					<label><?php echo Mage::helper('marketplace')->__('Description') ?>:</label>
					<div class="input-box">
						<textarea name="description" id="description" rows="5" cols="75" ><?php echo $loadpro->getDescription(); ?></textarea>
					</div>
				</li>
				<li>
					<label><?php echo Mage::helper('marketplace')->__('Short Description') ?>:</label>
					<div class="input-box">
						<textarea name="short_description" id="short_description" rows="5" cols="75"><?php echo $loadpro->getShortDescription();?></textarea>
					</div>
				</li>
				<li>
					<label class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('SKU') ?>:</label>
					<div class="input-box">
						<input name="sku" id="sku" class="input-text required-entry" value="<?php  echo $loadpro->getsku(); ?>"/> 
					</div>
					<div id="skuavail" >
						<span class="success-msg skuavailable"><?php echo Mage::helper('marketplace')->__('SKU Available') ?></span>
					</div>
					<div id="skunotavail" >
						<span class="error-msg skunotavailable"><?php echo Mage::helper('marketplace')->__('SKU Already Exist') ?></span>
					</div>
				</li>
				<li>
					<label class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Price') ?>:</label>
					<div class="input-box">
						<input type="price" class="required-entry validate-zero-or-greater input-text" name="price" id="price" value="<?php  echo $loadpro->getPrice(); ?>" />
					</div>
				</li>
				<li>
					<label class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Stock') ?>:</label>
					<div class="input-box">
						<input type="stock" class="required-entry validate-number input-text" name="stock" id="stock" value="<?php echo $qtyStock; ?>"/>
					</div>
				</li>
				<li>
					<label class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Weight') ?>:</label>
					<div class="input-box">
						<input type="weight" class="required-entry validate-number validate-zero-or-greater validate-number-range number-range-0-99999999.9999 input-text" name="weight" id="weight"  value="<?php echo $loadpro->getWeight();?>"/>
					</div>
				</li>
				<li>
					<label><?php echo Mage::helper('marketplace')->__('Sample Image') ?>:</label>
					<div class="input-box">
						<input type='file' name='images'/>
						<br>
						<a class="wk_add_image" href='#' onClick='showOtherImage(); return false;'><?php echo Mage::helper('marketplace')->__("Add Other Image");?></a><br/>
						<div id='otherimages'></div>
						<div class="image_set">
							<?php $_product = Mage::getModel('catalog/product')->load($loadpro->getId())->getMediaGalleryImages();
							 if($_product) {  ?>
								<?php $i=0;
								  foreach($_product as $_image) { 
								  $i++; 
								  ?>
								  <div class="setimage">
									  <img id="<?php echo $_image->getFile(); ?>" pid="<?php echo $loadpro->getId(); ?>" src="<?=$this->helper('catalog/image')->init($_product, 'thumbnail',$_image->getFile())->resize(200, 130); ?>" width="50" height="50" alt="<?=$this->htmlEscape($_image->getLabel());?>" title="<?=$this->htmlEscape($_image->getLabel()); ?>" />
									  <span class="wk_imagedelete" title="Delete"><?php echo Mage::helper('marketplace')->__('X') ?></span>
								  </div>
							   <?php  } 
							   } ?>
						</div>
					</div>
				</li>
				<?php echo $this->getChildHtml();?>
			</ul>
		</div>
		<div class="buttons-set">
			<p class="required">* <?php echo Mage::helper('marketplace')->__('Required Fields') ?></p>
			<button class="button" title="Save" type="submit" id="save_butn">
				<span><span><?php echo Mage::helper('marketplace')->__('Save') ?></span></span>
			</button>
			<p class="back-link">
				<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo Mage::helper('marketplace')->__('Back') ?></a>
			</p>
		</div>
	</form>
<script> 
var $wk_jq=jQuery.noConflict();
(function($wk_jq){
	var newCustomerProductForm = new VarienForm('form-customer-product-editPost', true);
	$wk_jq('#save_butn').click(function(){
			if(newCustomerProductForm.validator.validate()!=false){
				$wk_jq('#save_butn span span').text('Saving..');
				$wk_jq('#save_butn').css('opacity','0.7');
			}
			
	});
	$wk_jq(function(){
		$wk_jq('input#sku').change(function(){
			var len=$wk_jq('input#sku').val();
			var len2=len.length;
			if(len2==0){
				alert("<?php echo Mage::helper('marketplace')->__('SKU can\'t be left empty') ?>");
				$wk_jq('div#skuavail').css('display','none');
				$wk_jq('div#skunotavail').css('display','none');
			}
			else{
				$wk_jq.ajax({
					url: "<?php echo Mage::getUrl('marketplace/marketplaceaccount/verifysku');?>",
					type: "POST",
					data: {sku:$wk_jq('input#sku').val()},
					dataType: 'html',
					success:function($data){
						$data=JSON.parse($data);
						if($data.avl==1){
							$wk_jq('div#skuavail').css('display','block');
							$wk_jq('div#skunotavail').css('display','none');
						}
						else{
							$wk_jq('div#skunotavail').css('display','block');
							$wk_jq('div#skuavail').css('display','none');
							$wk_jq("input#sku").attr('value','');
						}
					}
				});
			}
		});
	
		$wk_jq('.image_set div').click(function(event){
			var dicisionapp=confirm('Sure Want To Delete Image');
			if(dicisionapp==true){
				var imag = $wk_jq(this).find('img').attr('id');
				$wk_jq.ajax({
					url: "<?php echo $this->getUrl('marketplace/marketplaceaccount/deleteimage');?>",
					type: "POST",
					data: {file:$wk_jq(this).find('img').attr('id'),pid:$wk_jq(this).find('img').attr('pid')},
					dataType: 'html',
					success:function(content){
						$wk_jq(this).remove();
					}
				});
				$wk_jq(this).remove();
			}		
		});
		$wk_jq('.image_set img').mouseover(function(event){
			$wk_jq(event.target).parent('div').find('span').css({display:'block'});
			$wk_jq(event.target).parent('div').find('img').css('opacity','0.4');
		});
		$wk_jq('.image_set img').mouseout(function(event){
			$wk_jq(event.target).parent('div').find('span').css({display:'none'});
			$wk_jq(event.target).parent('div').find('img').css('opacity','1');
		});

		$wk_jq('.image_set span').mouseover(function(event){
			$wk_jq(event.target).parent('div').find('span').css({display:'block'});
			$wk_jq(event.target).parent('div').find('img').css('opacity','0.4');
		});
		$wk_jq('.image_set span').mouseout(function(event){
			$wk_jq(event.target).parent('div').find('span').css({display:'none'});
			$wk_jq(event.target).parent('div').find('img').css('opacity','1');
		});
	})
})($wk_jq);
</script>	

<script type="text/javascript">
	var newCustomerProductForm = new VarienForm('form-customer-product-editPost', true);
	var i=2;
	function showOtherImage() {
		var newdiv = document.createElement('div');
		newdiv.setAttribute("id","childDiv"+i);
		newdiv.innerHTML = "<input type='file' name='images"+i+"' /><a href=\"javascript:;\" onclick=\"removeEvent('childDiv"+i+"')\"><?php echo Mage::helper('marketplace')->__('Remove') ?></a>";
		var ni = document.getElementById('otherimages');
		ni.appendChild(newdiv);
		i++;
	}

	function removeEvent(divNum){
		var d = document.getElementById('otherimages');
		var olddiv = document.getElementById(divNum);
		d.removeChild(olddiv);
		i--;
	}
</script>
<?php
}else{
	echo Mage::helper('marketplace')->__("<h2 class='wk_new_msg'>YOU ARE NOT AUTHORIZE TO EDIT THIS PRODUCT..</h2>");
}
 }else{
	echo Mage::helper('marketplace')->__("<h2 class='wk_new_msg'>FOR BECOME SELLER CONTACT TO ADMIN..</h2>");
}?>