<?php 
$marketplacelabel=Mage::getStoreConfig('marketplace/marketplace_options/marketplacelabel'); 
$marketplacebutton=Mage::getStoreConfig('marketplace/marketplace_options/marketplacebutton');
$marketplaceprofile=Mage::getStoreConfig('marketplace/marketplace_options/marketplaceprofile');
?>
<div id="wk_mp_header">
	<h1><?php echo $marketplacelabel; ?></h1>
	<p>
		<a class="button-large" href="<?php echo $this->getUrl('customer/account/create/'); ?>"><?php echo $marketplacebutton; ?></a>
	</p>
</div>
<div class="wk_profiledata">
<?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($marketplaceprofile); ?>
</div>
<div class="list_seller_product">
	<div class="label">
		<?php echo Mage::helper('marketplace')->__('Seller List'); ?>
	</div>
	<?php $sellerlist=Mage::getModel('marketplace/userprofile')
								->getCollection()
								->addFieldToFilter('partnerstatus',array('eq'=>'Seller'))
								->addFieldToFilter('wantpartner',array('eq'=>1))
								->setOrder('autoid','DESC')
								->setPageSize(8)
								->setCurPage(1); 
		foreach($sellerlist as $seller){
			$customerid=$seller->getMageuserid();
			$customer=Mage::getModel('customer/customer')->load($customerid);
			$logo=$seller->getlogopic()==''?"noimage.png":$seller->getlogopic();
			$logo=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$logo; ?>
			<a href="<?php echo  Mage::getUrl()."marketplace/seller/profile/".$seller->getProfileurl(); ?>">
				<img alt="<?php echo $customer->getFirstname()." ".$customer->getLastname(); ?>" title="<?php echo $customer->getFirstname()." ".$customer->getLastname(); ?>" src="<?php echo $logo;?>">
				<div class="mp_landing_hover">
					<span><?php echo $seller->getProfileurl(); ?></span>
				</div>
			</a> 
		<?php } ?>
</div>
<div class="list_seller_product">
	<div class="label">
		<?php echo Mage::helper('marketplace')->__('Latest Product Added'); ?>
	</div>
	<?php 
	$partnerId=Mage::getSingleton('customer/session')->getCustomerId();	
	$partnerproducts = Mage::getModel('marketplace/product')
								->getCollection()				
								->addFieldToFilter('status', array('neq' => 2))					
								->setOrder('mageproductid','DESC')
								->setPageSize(8)
								->setCurPage(1);								
	foreach($partnerproducts as $product){ 		
		$product=Mage::getModel('catalog/product')->load($product->getMageproductid()); ?>
		<a href="<?php echo $product->getProductUrl();?>">
			<img src="<?php echo $product->getImageUrl();?>" title="<?php echo $product->getName(); ?>" alt="<?php echo $product->getName(); ?>"></img>
			<div class="mp_landing_hover">
				<span><?php echo $product->getName(); ?></span>
			</div>
		</a>
	<?php } ?>
</div>