<?php 
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
if($isPartner==1){
	$cur_symbol=Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
?>
	<div class="page-title">
		<h1><?php echo Mage::helper('marketplace')->__('My Order History') ?></h1>
	</div>
	<div class="fieldset">
		<h2 class="legend"><?php echo Mage::helper('marketplace')->__('Order History') ?></h2>
		<div class="wk_orderbox">
			<?php if(count($this->getCollection())==0){ ?>
				<div class="wk_emptymsg"><?php echo "no order available"; ?></div>
			<?php }?>
			<?php $m=0;
			foreach($this->getCollection() as $res){
				$order = Mage::getModel('sales/order')->load($res['mageorderid']);
				$status=$order->getStatus();
				$name=$order->getCustomerName();
				if($res['mageorderid']>0){?>
					<div class="wk_orderbox">
						<div class="wk_dash_orderstatus">
							<label for="name" class="wk_dash_label">
								<?php if($status=='pending') {?>
									<div class="status pending"><?php echo strtoupper($status); ?> </div>
								<?php }?>
								<?php if($status=='canceled') {?>
									<div class="status canceled"><?php echo strtoupper($status); ?> </div>
								<?php }?>
								<?php if($status=='complete') {?>
									<div class="status complete"><?php echo strtoupper($status); ?> </div>
								<?php }?>
								<?php if($status=='processing') {?>
									<div class="status processing"><?php echo strtoupper($status); ?> </div>
								<?php }?>
								<p class="wk_order_clear"><?php echo "<br>".$res['cleared_at']; ?></p> 
							</label> 
						</div>
						<div class="wk_dash_orderstatus">
							<label for="name" class="wk_dash_label">
								<div class="color"><?php echo Mage::helper('marketplace')->__('Order') ?> #<?php echo $res['magerealorderid']; ?></div>
								<div class="name"><?php echo Mage::helper('marketplace')->__('By') ?><?php  echo " ".$name; ?><br/>
								<?php
								  $pname=explode(',',$res['mageproname']);
								  $pid=explode(',',$res['mageproid']);
									for($p=0;$p<=count($pid);$p++){
									if($pname[$p]){
											echo "<p class='product_label'>".$pname[$p]."&nbsp;</p>"; $proid[$m]=$pid[$p];
											}
										
									}?>
								</div> 
							</label> 
						</div>
						<div class="wk_dash_orderstatus">
							<label for="name" class="wk_dash_label cost"><?php echo $cur_symbol.$res['actualparterprocost'];?> </label> 
						</div>
					</div>
					<div class="wk_clear"></div>
				<?php }
			} 	?>
			<?php echo $this->getPagerHtml(); ?>				
		</div>
	</div>
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo Mage::helper('marketplace')->__('Back') ?></a>
		</p>
	</div>
<?php 
	}else{
	echo Mage::helper('marketplace')->__("<h2 class='wk_new_msg'>FOR BECOME SELLER CONTACT TO ADMIN..</h2>");
}?>