<?php 
	$isPartner= Mage::getModel('marketplace/userprofile')->isPartner(); 
	if($isPartner==1){
		?>
<script type="text/javascript">
if (typeof jQuery == 'undefined'){
    document.write(unescape("%3Cscript src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>
<?php if(count($this->getCollection())==0){ ?>
	<div class="fieldset">
		<h2 class="legend"><?php echo Mage::helper('marketplace')->__('Product List') ?></h2>
		<div class="wk_emptymsg">
			<?php echo Mage::helper('marketplace')->__('No Product Available') ?>
		</div>
	</div>
<?php } 
else{ ?>

<div>	
	<div class="page-title">
		<h1><?php echo Mage::helper('marketplace')->__('My Product List') ?></h1>
	</div>
	<div class="fieldset">
		<h2 class="legend"><?php echo Mage::helper('marketplace')->__('Product List') ?></h2>
		<?php echo $this->getPagerHtml(); ?>
		<div class="wk_content">
			<div class="head">			
				<span class="label name">
					<?php echo Mage::helper('marketplace')->__('Product Name')?>
				</span>
				<span class="label">
					<?php echo Mage::helper('marketplace')->__('Image')?>
				</span>
				<span class="label price">
					<?php echo Mage::helper('marketplace')->__('Price')?>
				</span>							
				<span class="label pro_status">
					<?php echo Mage::helper('marketplace')->__('Status')?>
				</span>
				<span class="label qty">
					<?php echo Mage::helper('marketplace')->__('Qty. Confirmed')?>
				</span>
				<span class="label qty">
					<?php echo Mage::helper('marketplace')->__('Qty. Pending')?>
				</span>
				<span class="label qty">
					<?php echo Mage::helper('marketplace')->__('Qty. Sold')?>
				</span>
				<span class="label">
					<?php echo Mage::helper('marketplace')->__('Earn Amount')?>
				</span>
				<span class="label">
					<?php echo Mage::helper('marketplace')->__('Action')?>
				</span>
			</div>
			<div class="wk_clear"></div>				
			<div class="wk_seller_product">
				<?php 
				foreach($this->getCollection() as $products){  
					$productMediaConfig = Mage::getModel('catalog/product_media_config');
					$salesdetail=Mage::getModel('marketplace/saleslist')->getSalesdetail($products->getEntityId());
				?>
					<div class="wk_row_view">
						<input type="hidden" class="hidden_id" value="<?php echo $products->getEntityId(); ?>" />
						<span class="label name" title="<?php echo $products->getName(); ?>">
						<?php 
							$productname=strlen($products->getName())>7?substr($products->getName(),0,7)."..":$products->getName();
							echo $productname;
						?>
						</span>
						<span class="label">
							<img src="<?php echo $productMediaConfig->getMediaUrl($products->getImage());?>" class="image" />
						</span>
						<span class="label">
							<?php echo Mage::app()->getStore()->formatPrice($products->getPrice())?>
						</span>
						<?php if($products->getStatus()==2) {	?> 			
								<span class="label pro_status">
									<?php echo Mage::helper('marketplace')->__('Pending')?>
								</span>
								<span class="label qty">
									<?php echo Mage::helper('marketplace')->__('Pending')?>
								</span>
								<span class="label qty">
									<?php echo Mage::helper('marketplace')->__('Pending')?>
								</span>
								<span class="label qty">
									<?php echo Mage::helper('marketplace')->__('Pending')?>
								</span>
								<span class="label price">
									<?php echo Mage::helper('marketplace')->__('Pending')?>
								</span>
							
						<?php }
						else{ 
							$id=$products->getId();
							$productsolddetail=Mage::getModel('marketplace/saleslist')->getProductSalesDetailById($id);
							$qtycom=0;
							$com=0;
							foreach($productsolddetail as $key){
								$qtycom+=$key['magequantity'];
								$com+=$key['actualparterprocost'];
							}	?>
							<span class="label pro_status">
								<?php echo Mage::helper('marketplace')->__('Approved')?>
							</span>
							<span class="label qty"><?php echo $salesdetail['quantitysoldconfirmed']; ?></span>
							<span class="label qty"><?php echo $salesdetail['quantitysoldpending'];	?></span>
							<span class="label qty">
								<?php echo $salesdetail['quantitysold']; ?>
							</span>
							<span class="label price">
								<?php echo $salesdetail['amountearned']; ?>
							</span>
						<?php } ?>
						<span class="label">
								<img src="<?php echo $this->getSkinUrl('marketplace/images/edit.gif'); ?>" alt="<?php echo Mage::helper('marketplace')->__('Edit')?>" title="<?php echo Mage::helper('marketplace')->__('Edit')?>" class="mp_edit"/> || 
								<img src="<?php echo $this->getSkinUrl('marketplace/images/delete.gif'); ?>" alt="<?php echo Mage::helper('marketplace')->__('Delete')?>" title="<?php echo Mage::helper('marketplace')->__('Delete')?>" class="mp_delete"/>
						</span>	
					</div>
					<div class="wk_clear"></div>
				<?php } ?>
			</div>
		</div>	
		<?php echo $this->getPagerHtml(); ?>		
	</div>	
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo Mage::helper('marketplace')->__('Back') ?></a>
		</p>
	</div>
</div>
<script> 
var $wk_jq=jQuery.noConflict();
(function($wk_jq){
	$wk_jq('.mp_edit').click(function(){
		var id=$wk_jq(this).parents('.wk_row_view').find('.hidden_id').val();
		var dicision=confirm('Sure Want To Edit Magento Product');
		if(dicision==true)
			window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedsimple/') ?>".concat("id/",id); 
	});
	$wk_jq('.mp_delete').click(function(){
		var id=$wk_jq(this).parents('.wk_row_view').find('.hidden_id').val();
		var dicision=confirm('<?php echo Mage::helper('marketplace')->__('Sure Want To Delete Magento Product')?>');
		if(dicision==true)
			window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/delete/') ?>".concat("id/",id);
	});
})($wk_jq);
</script>
<?php }
}else{
	echo Mage::helper('marketplace')->__("<h2 class='wk_new_msg'>FOR BECOME SELLER CONTACT TO ADMIN..</h2>");
}?>