

<div class="row">
  <!-- <div class="videoWrapper">
    <iframe src="https://www.youtube.com/embed/n_dZNLr2cME?autoplay=1&amp;loop=1&amp;cc_load_policy=1rel=0&amp;controls=0&amp;showinfo=0&amp;playlist=n_dZNLr2cME" frameborder="0" width="100%" height="349"></iframe>
    <div class="video-content">
      <h3>THE TIME LESS STORE</h3>
    </div>
  </div> -->
  <div class="col-lg-12 pad-l-r-0">
  <div id="owl-demo" class="owl-carousel owl-theme" >
 
  <div class="item"><img src="http://127.0.0.1/parthas/media//wysiwyg/parthas-banner/bb.jpg" alt="The Last of us"></div>
  <div class="item"><img src="http://127.0.0.1/parthas/media//wysiwyg/parthas-banner/bb.jpg" alt="GTA V"></div>
  <div class="item"><img src="http://127.0.0.1/parthas/media//wysiwyg/parthas-banner/bb.jpg" alt="Mirror Edge"></div>
 
</div>
</div>  
</div>
<div class="bann row">
  <div class="pad-l-r-0 col-lg-6 border-t-r">
    <!-- <span class="b-title clr-t">MEN</span> -->
    <img class="sub-banner-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/men.jpg" alt="men" />
  </div>
  <div class="pad-l-r-0 col-lg-6">
   <!--  <span class="b-1-title clr-t">WOMEN</span> -->
    <img class="sub-banner-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/women-c.jpg" alt="women" />
  </div>
</div>
<div class="row">
  <div class="pad-l-r-0 col-lg-6 border-clr-w">
    <img class="sub-banner-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/summer.jpg" alt="men" />
  </div>
  <div class="pad-l-r-0 col-lg-6 ">
    <img class="sub-banner-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/w-banner.jpg" alt="women" />
  </div>
</div>
<div class="row camp-pad">
  <div class="col-md-3 pad-l-r-0">
    <div class="cam-banner">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/camp-1.jpg" alt="" />
    </div>
    <div class="cam-bg">
      <label class="camp-label">MEN</label>
      <p class="cam-p-content">Distressed jeans are bringing the 80s back and how. Have you got your pair yet?</p>
    </div>
  </div>
  <div class="col-md-3 pad-l-r-0">
    <div class="cam-bg">
      <label class="camp-label">MEN</label>
      <p class="cam-p-content">Distressed jeans are bringing the 80s back and how. Have you got your pair yet?</p>
    </div>
    <div class="cam-banner">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/camp-1.jpg" alt="" />
    </div>
  </div>
  <div class="col-md-3 pad-l-r-0">
    <div class="cam-banner">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/camp-1.jpg" alt="" />
    </div>
    <div class="cam-bg">
      <label class="camp-label">MEN</label>
      <p class="cam-p-content">Distressed jeans are bringing the 80s back and how. Have you got your pair yet?</p>
    </div>
  </div>
  <div class="col-md-3 pad-l-r-0">
    <div class="cam-bg">
      <label class="camp-label">MEN</label>
      <p class="cam-p-content">Distressed jeans are bringing the 80s back and how. Have you got your pair yet?</p>
    </div>
    <div class="cam-banner">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/camp-1.jpg" alt="" />
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 pad-l-r-0 back-theme">
    <div class="showroom-detail">
      <h3>Our showroom</h3>
      <p>___</p>
      <div class="sub-add-details">
        <address>Power House Road,</br>East Fort,</br>Thiruvananthapuram,</br>    Kerala 695036</address>
      </div>
      <div class="contact-detail p-40">
        <p class="m-0">P 04712461949</p>
        <p class="m-0">E hello@parthasonline.com</p>
      </div>
    </div>
  </div>
  <div class="col-md-6 pad-l-r-0">
    <div id="map" style="width: 100%; height: 300px;">&nbsp;</div>
    <div class="map-sub-details clr-t">
      <address>
        <label>Cochin branch:</label></br>No.1774,</br> Mahatma Gandhi Rd,</br>Ernakulam South

        <p class="p-40">
          <label>Kottayam branch:</label></br> No 119, K. K. Road,</br> Kottayam
        </p>
      </address>
    </div>
  </div>
</div>
<div class="row footer">
  <div class="footer">
    <div class="col-md-6">
      <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>/wysiwyg/parthas-banner/logo.png" alt="" />
    </div>
    <div class="col-md-6 text-right">
      <ul class="footer-links">
        <li>
          <a href=" ">HOME</a>
        </li>
        <li>
          <a href=" ">FAQ'S</a>
        </li>
        <li>
          <a href=" ">RETURN POLICY</a>
        </li>
        <li>
          <a href=" ">FACEBOOK</a>
        </li>
        <li>
          <a href=" ">INSTAGRAM</a>
        </li>
      </ul>
    </div>
  </div>
</div>
<script type="text/javascript">
$mt(document).ready(function() {
 
  $mt("#owl-demo").owlCarousel({
 
     navigation: true, // Show next and prev buttons
    slideSpeed: 300,
    pagination: false,
    paginationSpeed: 400,
    singleItem: true,
    loop: true,
    items:1,
    rewindNav:false,
    autoPlay: true,
    autoPlaySpeed: 10,
    autoPlayTimeout: 5000,
    autoPlayHoverPause: true
 
  });
 
 $mt( ".owl-prev").html('<i class="fa fa-chevron-left"></i>');
 $mt( ".owl-next").html('<i class="fa fa-chevron-right"></i>');  
});
function myMap() {
  var myCenter = new google.maps.LatLng(51.508742,-0.120850);
  var mapCanvas = document.getElementById("map");
  var mapOptions = {center: myCenter, zoom: 15, zoomControl: false,scaleControl: false,
      // styles: [
      //       {elementType: 'geometry', stylers: [{color: '#242f3e'}]},
      //       {elementType: 'labels.text.stroke', stylers: [{color: '#242f3e'}]},
      //       {elementType: 'labels.text.fill', stylers: [{color: '#746855'}]},
      //       {
      //         featureType: 'administrative.locality',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#d59563'}]
      //       },
      //       {
      //         featureType: 'poi',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#d59563'}]
      //       },
      //       {
      //         featureType: 'poi.park',
      //         elementType: 'geometry',
      //         stylers: [{color: '#263c3f'}]
      //       },
      //       {
      //         featureType: 'poi.park',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'road',
      //         elementType: 'geometry',
      //         stylers: [{color: '#38414e'}]
      //       },
      //       {
      //         featureType: 'road',
      //         elementType: 'geometry.stroke',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'road',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'road.highway',
      //         elementType: 'geometry',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'road.highway',
      //         elementType: 'geometry.stroke',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'road.highway',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'transit',
      //         elementType: 'geometry',
      //         stylers: [{color: '#fce9eb'}]
      //       },
      //       {
      //         featureType: 'transit.station',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#d59563'}]
      //       },
      //       {
      //         featureType: 'water',
      //         elementType: 'geometry',
      //         stylers: [{color: '#17263c'}]
      //       },
      //       {
      //         featureType: 'water',
      //         elementType: 'labels.text.fill',
      //         stylers: [{color: '#515c6d'}]
      //       },
      //       {
      //         featureType: 'water',
      //         elementType: 'labels.text.stroke',
      //         stylers: [{color: '#17263c'}]
      //       }
      //     ],

    disableDefaultUI: true};
  var map = new google.maps.Map(mapCanvas, mapOptions);
  var marker = new google.maps.Marker({position:myCenter});
  marker.setMap(map); 

}


</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=&amp;callback=myMap"></script>
<script type="text/javascript">




</script>