<?php
$product = Mage::getModel('catalog/product');
$attributes = Mage::getResourceModel('eav/entity_attribute_collection')
                  ->setEntityTypeFilter($product->getResource()->getTypeId())
                  ->addFieldToFilter('attribute_code', 'brand');
$attribute = $attributes->getFirstItem()->setEntity($product->getResource());
$manufacturers = $attribute->getSource()->getAllOptions(true,true);
$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'brand');

?>

<div class="brandLogoWrapper row">
    <?php $connection = Mage::getModel('core/resource')->getConnection('core_read');
$sql = 'SELECT * FROM `eav_attribute_option`';
$option_images = $connection->fetchAll($sql);
 $catId = Mage::getModel('catalog/layer')->getCurrentCategory()->getId(); 
 $category = Mage::getModel('catalog/category')->load($catId); 
 $catUrl = $category->getUrl(); 
 foreach ($option_images as $option_image){ 
 $imapath=$option_image['image'];
 if($imapath){
 ?>
 <a class="trackClickPage small-6 medium-3 column" data-click="hp_brands_1_alegria" href="<?php echo $this->getUrl('brands-product-listing').'?brand='.$option_image['option_id'] ?>">

<img class="removeTopBorder removeLeftBorder" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'media/'.$imapath; ?>"> 
</a>

 <?php } } ?>
</div>

<?php
echo "Hello";
$collectionfetch = Mage::getModel('marketplace/userprofile')->getCollection();
$record = array();
foreach($collectionfetch as $id)
{
    $record[] = $id->getmageuserid();
}
$collection = Mage::getModel('customer/customer')->getCollection()
    ->addNameToSelect()
    ->addAttributeToSelect('email');
  //  ->addAttributeToSelect('created_at')
  //  ->addAttributeToSelect('group_id')
 //   ->joinAttribute('billing_postcode', 'customer_address/postcode', 'default_billing', null, 'left')
   // ->joinAttribute('billing_city', 'customer_address/city', 'default_billing', null, 'left')
   // ->joinAttribute('billing_telephone', 'customer_address/telephone', 'default_billing', null, 'left')
   // ->joinAttribute('billing_region', 'customer_address/region', 'default_billing', null, 'left')
   // ->joinAttribute('billing_country_id', 'customer_address/country_id', 'default_billing', null, 'left');
$collection->addAttributeToFilter('entity_id', array('in' => $record));
$collection->joinTable('marketplace/userprofile', 'mageuserid=entity_id', array('*'), null, 'left');
foreach($collection as $collections){
    echo $collections->getEmail();
    echo "<br>";
}
//var_dump($collection);

?>
